AWSTemplateFormatVersion: 2010-09-09
Parameters:
  Region:
    Type: String
    Default: us-east-1
  VpcAz:
    Type: AWS::EC2::AvailabilityZone::Name
    Default: us-east-1c
Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: yamlClusterName